version: '2.4'

services:
  # Test environment
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: test
  test-integration:
    extends:
      service: test
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      TEST_OUTPUT_DIR: /reports
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  # Database service
  db:
    image: mariadb:10.5
    healthcheck:
      test: mysqlshow -u $$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 3s
      retries: 10
    environment:
      MYSQL_DATABASE: todobackend
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  # Release environment
  release-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    image: release
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: 'true'
      DJANGO_SETTINGS_MODULE: todobackend.settings.release
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
    ports:
      - 8000:8000
    command:
      - uwsgi
      - --http=0.0.0.0:8000
      - --module=todobackend.wsgi
      - --master
      - --check-static=/public
      - --die-on-term
      - --processes=4
      - --threads=10